jdk:
  - openjdk17

before_install:
  - chmod +x gradlew

install:
  - ./gradlew :uploadservice:clean
  - ./gradlew :uploadservice:assembleRelease
  - ./gradlew :uploadservice:releaseSourcesJar
  - ./gradlew :uploadservice:generatePomFileForReleasePublication

env:
  ANDROID_HOME: /usr/local/android-sdk
  ANDROID_SDK_ROOT: /usr/local/android-sdk
  ANDROID_NDK_HOME: /usr/local/android-ndk
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
