jdk:
  - openjdk17

install:
  - echo "sdk.dir=/usr/local/android-sdk" > uploadservice-ftp/local.properties
  - echo "sdk.dir=/usr/local/android-sdk" > uploadservice-okhttp/local.properties
  - echo "sdk.dir=/usr/local/android-sdk" > uploadservice/local.properties
  - ./gradlew clean
  - ./gradlew assembleRelease
  - ./gradlew releaseSourcesJar
  - ./gradlew generatePomFileForReleasePublication
