jdk:
  - openjdk17

before_install:
  - chmod +x gradlew
  - mkdir -p $ANDROID_HOME/licenses
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license

install:
  - ./gradlew :uploadservice:clean
  - ./gradlew :uploadservice:assembleRelease
  - ./gradlew :uploadservice:releaseSourcesJar
  - ./gradlew :uploadservice:generatePomFileForReleasePublication

env:
  ANDROID_HOME: /usr/local/android-sdk
  ANDROID_SDK_ROOT: /usr/local/android-sdk
  ANDROID_NDK_HOME: /usr/local/android-ndk
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
