jdk:
  - openjdk17

before_install:
  - chmod +x gradlew

install:
  - ./gradlew :uploadservice:clean
  - ./gradlew :uploadservice:assembleRelease
  - ./gradlew :uploadservice:releaseSourcesJar
  - ./gradlew :uploadservice:generatePomFileForReleasePublication

# Skip other modules to avoid Javadoc generation issues
env:
  SKIP_JAVADOC: 1
  ANDROID_SDK_ROOT: /usr/local/android-sdk
  ANDROID_HOME: /usr/local/android-sdk
